audio:
	GOOGLE_APPLICATION_CREDENTIALS=/Users/emicklei/goProjects/github.com/emicklei/gspeech/service-account-key.json gspeech -v "en-GB-Wavenet-F" -i "test1.ssml"
	GOOGLE_APPLICATION_CREDENTIALS=/Users/emicklei/goProjects/github.com/emicklei/gspeech/service-account-key.json gspeech -v "en-GB-Wavenet-F" -i "test2.ssml"

preso:
	cd .. && go install && cd test && audiovisio -c test.yaml -o test.html