package audiovisio

func stylesheetSource() string {
	return `

	/*  This file is GENERATED by the audiovisio tool
	 *  It will NOT be overwritten by the tool.
	 */ 

	 body {
		font: 14px Arial, sans-serif;
		color: white;
		margin: 0px;
	}
	
	.box {
		display: flex;
		align-items: center;
		justify-content: center;
	}	  

	a {
	  color: lightgray;
	}
	
	.wrapper {
	  display: flex;  
	  flex-flow: row wrap;
	  font-weight: bold;
	  text-align: center;
	}
	
	.wrapper > * {
	  padding: 10px;
	  flex: 1 100%;
	}
	
	.header {
	  background: rgb(67, 64, 126);
	}
	
	.footer {
	  background:  rgb(67, 64, 126);
	}
	
	.main {
	  text-align: left;
	  background: rgb(67, 64, 126);
	  align-content: center
	}
	
	.aside-1 {
	  background:  rgb(8, 5, 62);
	}
	
	.aside-2 {
	  background: rgb(8, 5, 62);
	}
	
	@media all and (min-width: 600px) {
	  .aside { flex: 1 0 0; }
	}
	
	@media all and (min-width: 800px) {
	  .main    { flex: 3 0px; }
	  .aside-1 { order: 1; } 
	  .main    { order: 2; }
	  .aside-2 { order: 3; }
	  .footer  { order: 4; }
	}
`
}
